(cl:defpackage hexapodservice-msg
  (:use )
  (:export
   "<HEXAPODSERVICEACTION>"
   "HEXAPODSERVICEACTION"
   "<HEXAPODSERVICEACTIONFEEDBACK>"
   "HEXAPODSERVICEACTIONFEEDBACK"
   "<HEXAPODSERVICEACTIONGOAL>"
   "HEXAPODSERVICEACTIONGOAL"
   "<HEXAPODSERVICEACTIONRESULT>"
   "HEXAPODSERVICEACTIONRESULT"
   "<HEXAPODSERVICEFEEDBACK>"
   "HEXAPODSERVICEFEEDBACK"
   "<HEXAPODSERVICEGOAL>"
   "HEXAPODSERVICEGOAL"
   "<HEXAPODSERVICERESULT>"
   "HEXAPODSERVICERESULT"
   "<LEG>"
   "LEG"
   "<LEGJOINT>"
   "LEGJOINT"
   "<LEGJOINTS>"
   "LEGJOINTS"
   "<LEGS>"
   "LEGS"
  ))

