; Auto-generated. Do not edit!


(cl:in-package hexapodservice-msg)


;//! \htmlinclude hexapodserviceFeedback.msg.html

(cl:defclass <hexapodserviceFeedback> (roslisp-msg-protocol:ros-message)
  ((ALLLEGS_fdbk
    :reader ALLLEGS_fdbk
    :initarg :ALLLEGS_fdbk
    :type hexapodservice-msg:leg
    :initform (cl:make-instance 'hexapodservice-msg:leg)))
)

(cl:defclass hexapodserviceFeedback (<hexapodserviceFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <hexapodserviceFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'hexapodserviceFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hexapodservice-msg:<hexapodserviceFeedback> is deprecated: use hexapodservice-msg:hexapodserviceFeedback instead.")))

(cl:ensure-generic-function 'ALLLEGS_fdbk-val :lambda-list '(m))
(cl:defmethod ALLLEGS_fdbk-val ((m <hexapodserviceFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hexapodservice-msg:ALLLEGS_fdbk-val is deprecated.  Use hexapodservice-msg:ALLLEGS_fdbk instead.")
  (ALLLEGS_fdbk m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <hexapodserviceFeedback>) ostream)
  "Serializes a message object of type '<hexapodserviceFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'ALLLEGS_fdbk) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <hexapodserviceFeedback>) istream)
  "Deserializes a message object of type '<hexapodserviceFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'ALLLEGS_fdbk) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<hexapodserviceFeedback>)))
  "Returns string type for a message object of type '<hexapodserviceFeedback>"
  "hexapodservice/hexapodserviceFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'hexapodserviceFeedback)))
  "Returns string type for a message object of type 'hexapodserviceFeedback"
  "hexapodservice/hexapodserviceFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<hexapodserviceFeedback>)))
  "Returns md5sum for a message object of type '<hexapodserviceFeedback>"
  "403f7a6b04ba80a9669cf3a75e8e9e8d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'hexapodserviceFeedback)))
  "Returns md5sum for a message object of type 'hexapodserviceFeedback"
  "403f7a6b04ba80a9669cf3a75e8e9e8d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<hexapodserviceFeedback>)))
  "Returns full string definition for message of type '<hexapodserviceFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%hexapodservice/leg ALLLEGS_fdbk~%~%~%================================================================================~%MSG: hexapodservice/leg~%hexapodservice/legjoint[6] leg~%~%================================================================================~%MSG: hexapodservice/legjoint~%float64 coxa~%float64 femur~%float64 tibia~%float64 tarsus~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'hexapodserviceFeedback)))
  "Returns full string definition for message of type 'hexapodserviceFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%hexapodservice/leg ALLLEGS_fdbk~%~%~%================================================================================~%MSG: hexapodservice/leg~%hexapodservice/legjoint[6] leg~%~%================================================================================~%MSG: hexapodservice/legjoint~%float64 coxa~%float64 femur~%float64 tibia~%float64 tarsus~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <hexapodserviceFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'ALLLEGS_fdbk))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <hexapodserviceFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'hexapodserviceFeedback
    (cl:cons ':ALLLEGS_fdbk (ALLLEGS_fdbk msg))
))
