# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hexapodservice/legs.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import hexapodservice.msg

class legs(genpy.Message):
  _md5sum = "283042c2b49d709689847698830e74a9"
  _type = "hexapodservice/legs"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """hexapodservice/legjoints[6] leg

================================================================================
MSG: hexapodservice/legjoints
int64[] coxa
int64[] femur
int64[] tibia
int64[] tarsus
"""
  __slots__ = ['leg']
  _slot_types = ['hexapodservice/legjoints[6]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       leg

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(legs, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.leg is None:
        self.leg = [hexapodservice.msg.legjoints() for _ in range(6)]
    else:
      self.leg = [hexapodservice.msg.legjoints() for _ in range(6)]

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      for val1 in self.leg:
        length = len(val1.coxa)
        buff.write(_struct_I.pack(length))
        pattern = '<%sq'%length
        buff.write(struct.pack(pattern, *val1.coxa))
        length = len(val1.femur)
        buff.write(_struct_I.pack(length))
        pattern = '<%sq'%length
        buff.write(struct.pack(pattern, *val1.femur))
        length = len(val1.tibia)
        buff.write(_struct_I.pack(length))
        pattern = '<%sq'%length
        buff.write(struct.pack(pattern, *val1.tibia))
        length = len(val1.tarsus)
        buff.write(_struct_I.pack(length))
        pattern = '<%sq'%length
        buff.write(struct.pack(pattern, *val1.tarsus))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.leg is None:
        self.leg = None
      end = 0
      self.leg = []
      for i in range(0, 6):
        val1 = hexapodservice.msg.legjoints()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sq'%length
        start = end
        end += struct.calcsize(pattern)
        val1.coxa = struct.unpack(pattern, str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sq'%length
        start = end
        end += struct.calcsize(pattern)
        val1.femur = struct.unpack(pattern, str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sq'%length
        start = end
        end += struct.calcsize(pattern)
        val1.tibia = struct.unpack(pattern, str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sq'%length
        start = end
        end += struct.calcsize(pattern)
        val1.tarsus = struct.unpack(pattern, str[start:end])
        self.leg.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      for val1 in self.leg:
        length = len(val1.coxa)
        buff.write(_struct_I.pack(length))
        pattern = '<%sq'%length
        buff.write(val1.coxa.tostring())
        length = len(val1.femur)
        buff.write(_struct_I.pack(length))
        pattern = '<%sq'%length
        buff.write(val1.femur.tostring())
        length = len(val1.tibia)
        buff.write(_struct_I.pack(length))
        pattern = '<%sq'%length
        buff.write(val1.tibia.tostring())
        length = len(val1.tarsus)
        buff.write(_struct_I.pack(length))
        pattern = '<%sq'%length
        buff.write(val1.tarsus.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.leg is None:
        self.leg = None
      end = 0
      self.leg = []
      for i in range(0, 6):
        val1 = hexapodservice.msg.legjoints()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sq'%length
        start = end
        end += struct.calcsize(pattern)
        val1.coxa = numpy.frombuffer(str[start:end], dtype=numpy.int64, count=length)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sq'%length
        start = end
        end += struct.calcsize(pattern)
        val1.femur = numpy.frombuffer(str[start:end], dtype=numpy.int64, count=length)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sq'%length
        start = end
        end += struct.calcsize(pattern)
        val1.tibia = numpy.frombuffer(str[start:end], dtype=numpy.int64, count=length)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sq'%length
        start = end
        end += struct.calcsize(pattern)
        val1.tarsus = numpy.frombuffer(str[start:end], dtype=numpy.int64, count=length)
        self.leg.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
