// Generated by gencpp from file link_com/heartbag.msg
// DO NOT EDIT!


#ifndef LINK_COM_MESSAGE_HEARTBAG_H
#define LINK_COM_MESSAGE_HEARTBAG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace link_com
{
template <class ContainerAllocator>
struct heartbag_
{
  typedef heartbag_<ContainerAllocator> Type;

  heartbag_()
    : kpa(0.0)
    , io()  {
      io.assign(0);
  }
  heartbag_(const ContainerAllocator& _alloc)
    : kpa(0.0)
    , io()  {
  (void)_alloc;
      io.assign(0);
  }



   typedef float _kpa_type;
  _kpa_type kpa;

   typedef boost::array<uint8_t, 7>  _io_type;
  _io_type io;





  typedef boost::shared_ptr< ::link_com::heartbag_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::link_com::heartbag_<ContainerAllocator> const> ConstPtr;

}; // struct heartbag_

typedef ::link_com::heartbag_<std::allocator<void> > heartbag;

typedef boost::shared_ptr< ::link_com::heartbag > heartbagPtr;
typedef boost::shared_ptr< ::link_com::heartbag const> heartbagConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::link_com::heartbag_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::link_com::heartbag_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace link_com

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'link_com': ['/home/sun/hexapod_service_ws/src/link_com/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::link_com::heartbag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::link_com::heartbag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::link_com::heartbag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::link_com::heartbag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::link_com::heartbag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::link_com::heartbag_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::link_com::heartbag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3975ec5bee3b3f6b04685f86ab5e40e0";
  }

  static const char* value(const ::link_com::heartbag_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3975ec5bee3b3f6bULL;
  static const uint64_t static_value2 = 0x04685f86ab5e40e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::link_com::heartbag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "link_com/heartbag";
  }

  static const char* value(const ::link_com::heartbag_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::link_com::heartbag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#kpa 真空度(0 ~ -100kpa)\n\
#io[x] = 0 代表第x腿吸盘与真空泵连通，吸盘与放气端口之间阻塞; io[x] = 1 代表第x腿吸盘与放气端口连通，吸盘与真空泵之间阻塞\n\
\n\
float32 kpa\n\
uint8[7] io\n\
";
  }

  static const char* value(const ::link_com::heartbag_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::link_com::heartbag_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.kpa);
      stream.next(m.io);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct heartbag_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::link_com::heartbag_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::link_com::heartbag_<ContainerAllocator>& v)
  {
    s << indent << "kpa: ";
    Printer<float>::stream(s, indent + "  ", v.kpa);
    s << indent << "io[]" << std::endl;
    for (size_t i = 0; i < v.io.size(); ++i)
    {
      s << indent << "  io[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.io[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LINK_COM_MESSAGE_HEARTBAG_H
