// Generated by gencpp from file link_com/hexcom.msg
// DO NOT EDIT!


#ifndef LINK_COM_MESSAGE_HEXCOM_H
#define LINK_COM_MESSAGE_HEXCOM_H

#include <ros/service_traits.h>


#include <link_com/hexcomRequest.h>
#include <link_com/hexcomResponse.h>


namespace link_com
{

struct hexcom
{

typedef hexcomRequest Request;
typedef hexcomResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct hexcom
} // namespace link_com


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::link_com::hexcom > {
  static const char* value()
  {
    return "4c6bf6a56b94d0854641b3cbd40fb9db";
  }

  static const char* value(const ::link_com::hexcom&) { return value(); }
};

template<>
struct DataType< ::link_com::hexcom > {
  static const char* value()
  {
    return "link_com/hexcom";
  }

  static const char* value(const ::link_com::hexcom&) { return value(); }
};


// service_traits::MD5Sum< ::link_com::hexcomRequest> should match 
// service_traits::MD5Sum< ::link_com::hexcom > 
template<>
struct MD5Sum< ::link_com::hexcomRequest>
{
  static const char* value()
  {
    return MD5Sum< ::link_com::hexcom >::value();
  }
  static const char* value(const ::link_com::hexcomRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::link_com::hexcomRequest> should match 
// service_traits::DataType< ::link_com::hexcom > 
template<>
struct DataType< ::link_com::hexcomRequest>
{
  static const char* value()
  {
    return DataType< ::link_com::hexcom >::value();
  }
  static const char* value(const ::link_com::hexcomRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::link_com::hexcomResponse> should match 
// service_traits::MD5Sum< ::link_com::hexcom > 
template<>
struct MD5Sum< ::link_com::hexcomResponse>
{
  static const char* value()
  {
    return MD5Sum< ::link_com::hexcom >::value();
  }
  static const char* value(const ::link_com::hexcomResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::link_com::hexcomResponse> should match 
// service_traits::DataType< ::link_com::hexcom > 
template<>
struct DataType< ::link_com::hexcomResponse>
{
  static const char* value()
  {
    return DataType< ::link_com::hexcom >::value();
  }
  static const char* value(const ::link_com::hexcomResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LINK_COM_MESSAGE_HEXCOM_H
