// Generated by gencpp from file link_com/hexcomRequest.msg
// DO NOT EDIT!


#ifndef LINK_COM_MESSAGE_HEXCOMREQUEST_H
#define LINK_COM_MESSAGE_HEXCOMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace link_com
{
template <class ContainerAllocator>
struct hexcomRequest_
{
  typedef hexcomRequest_<ContainerAllocator> Type;

  hexcomRequest_()
    : chose(0)
    , pwm(0)
    , io()  {
      io.assign(0);
  }
  hexcomRequest_(const ContainerAllocator& _alloc)
    : chose(0)
    , pwm(0)
    , io()  {
  (void)_alloc;
      io.assign(0);
  }



   typedef uint8_t _chose_type;
  _chose_type chose;

   typedef uint8_t _pwm_type;
  _pwm_type pwm;

   typedef boost::array<uint8_t, 7>  _io_type;
  _io_type io;





  typedef boost::shared_ptr< ::link_com::hexcomRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::link_com::hexcomRequest_<ContainerAllocator> const> ConstPtr;

}; // struct hexcomRequest_

typedef ::link_com::hexcomRequest_<std::allocator<void> > hexcomRequest;

typedef boost::shared_ptr< ::link_com::hexcomRequest > hexcomRequestPtr;
typedef boost::shared_ptr< ::link_com::hexcomRequest const> hexcomRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::link_com::hexcomRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::link_com::hexcomRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace link_com

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'link_com': ['/home/sun/hexapod_service_ws/src/link_com/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::link_com::hexcomRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::link_com::hexcomRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::link_com::hexcomRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::link_com::hexcomRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::link_com::hexcomRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::link_com::hexcomRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::link_com::hexcomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b691a199974dd65355429c066120d3b8";
  }

  static const char* value(const ::link_com::hexcomRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb691a199974dd653ULL;
  static const uint64_t static_value2 = 0x55429c066120d3b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::link_com::hexcomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "link_com/hexcomRequest";
  }

  static const char* value(const ::link_com::hexcomRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::link_com::hexcomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
uint8 chose\n\
uint8 pwm\n\
uint8[7] io\n\
";
  }

  static const char* value(const ::link_com::hexcomRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::link_com::hexcomRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.chose);
      stream.next(m.pwm);
      stream.next(m.io);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct hexcomRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::link_com::hexcomRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::link_com::hexcomRequest_<ContainerAllocator>& v)
  {
    s << indent << "chose: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.chose);
    s << indent << "pwm: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pwm);
    s << indent << "io[]" << std::endl;
    for (size_t i = 0; i < v.io.size(); ++i)
    {
      s << indent << "  io[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.io[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LINK_COM_MESSAGE_HEXCOMREQUEST_H
