// Generated by gencpp from file link_com/hexcomResponse.msg
// DO NOT EDIT!


#ifndef LINK_COM_MESSAGE_HEXCOMRESPONSE_H
#define LINK_COM_MESSAGE_HEXCOMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace link_com
{
template <class ContainerAllocator>
struct hexcomResponse_
{
  typedef hexcomResponse_<ContainerAllocator> Type;

  hexcomResponse_()
    : back()  {
    }
  hexcomResponse_(const ContainerAllocator& _alloc)
    : back(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _back_type;
  _back_type back;





  typedef boost::shared_ptr< ::link_com::hexcomResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::link_com::hexcomResponse_<ContainerAllocator> const> ConstPtr;

}; // struct hexcomResponse_

typedef ::link_com::hexcomResponse_<std::allocator<void> > hexcomResponse;

typedef boost::shared_ptr< ::link_com::hexcomResponse > hexcomResponsePtr;
typedef boost::shared_ptr< ::link_com::hexcomResponse const> hexcomResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::link_com::hexcomResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::link_com::hexcomResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace link_com

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'link_com': ['/home/sun/hexapod_service_ws/src/link_com/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::link_com::hexcomResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::link_com::hexcomResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::link_com::hexcomResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::link_com::hexcomResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::link_com::hexcomResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::link_com::hexcomResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::link_com::hexcomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c4a1d3ec3f5c241f65fed707d363d25e";
  }

  static const char* value(const ::link_com::hexcomResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc4a1d3ec3f5c241fULL;
  static const uint64_t static_value2 = 0x65fed707d363d25eULL;
};

template<class ContainerAllocator>
struct DataType< ::link_com::hexcomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "link_com/hexcomResponse";
  }

  static const char* value(const ::link_com::hexcomResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::link_com::hexcomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string back\n\
\n\
";
  }

  static const char* value(const ::link_com::hexcomResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::link_com::hexcomResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.back);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct hexcomResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::link_com::hexcomResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::link_com::hexcomResponse_<ContainerAllocator>& v)
  {
    s << indent << "back: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.back);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LINK_COM_MESSAGE_HEXCOMRESPONSE_H
