// Generated by gencpp from file hexapod_msgs/LegsJoints.msg
// DO NOT EDIT!


#ifndef HEXAPOD_MSGS_MESSAGE_LEGSJOINTS_H
#define HEXAPOD_MSGS_MESSAGE_LEGSJOINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <hexapod_msgs/LegJoints.h>

namespace hexapod_msgs
{
template <class ContainerAllocator>
struct LegsJoints_
{
  typedef LegsJoints_<ContainerAllocator> Type;

  LegsJoints_()
    : leg()  {
    }
  LegsJoints_(const ContainerAllocator& _alloc)
    : leg()  {
  (void)_alloc;
      leg.assign( ::hexapod_msgs::LegJoints_<ContainerAllocator> (_alloc));
  }



   typedef boost::array< ::hexapod_msgs::LegJoints_<ContainerAllocator> , 6>  _leg_type;
  _leg_type leg;




  typedef boost::shared_ptr< ::hexapod_msgs::LegsJoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hexapod_msgs::LegsJoints_<ContainerAllocator> const> ConstPtr;

}; // struct LegsJoints_

typedef ::hexapod_msgs::LegsJoints_<std::allocator<void> > LegsJoints;

typedef boost::shared_ptr< ::hexapod_msgs::LegsJoints > LegsJointsPtr;
typedef boost::shared_ptr< ::hexapod_msgs::LegsJoints const> LegsJointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hexapod_msgs::LegsJoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hexapod_msgs::LegsJoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hexapod_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'hexapod_msgs': ['/home/quan/hexapod_service_ws/src/hexapod_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hexapod_msgs::LegsJoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hexapod_msgs::LegsJoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hexapod_msgs::LegsJoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hexapod_msgs::LegsJoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hexapod_msgs::LegsJoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hexapod_msgs::LegsJoints_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hexapod_msgs::LegsJoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "77281f1f9c4cd29d21908d690db99185";
  }

  static const char* value(const ::hexapod_msgs::LegsJoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x77281f1f9c4cd29dULL;
  static const uint64_t static_value2 = 0x21908d690db99185ULL;
};

template<class ContainerAllocator>
struct DataType< ::hexapod_msgs::LegsJoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hexapod_msgs/LegsJoints";
  }

  static const char* value(const ::hexapod_msgs::LegsJoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hexapod_msgs::LegsJoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hexapod_msgs/LegJoints[6] leg\n\
================================================================================\n\
MSG: hexapod_msgs/LegJoints\n\
float64 coxa\n\
float64 femur\n\
float64 tibia\n\
float64 tarsus\n\
";
  }

  static const char* value(const ::hexapod_msgs::LegsJoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hexapod_msgs::LegsJoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.leg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LegsJoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hexapod_msgs::LegsJoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hexapod_msgs::LegsJoints_<ContainerAllocator>& v)
  {
    s << indent << "leg[]" << std::endl;
    for (size_t i = 0; i < v.leg.size(); ++i)
    {
      s << indent << "  leg[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::hexapod_msgs::LegJoints_<ContainerAllocator> >::stream(s, indent + "    ", v.leg[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEXAPOD_MSGS_MESSAGE_LEGSJOINTS_H
