// Auto-generated. Do not edit!

// (in-package hexapodservice.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class hexapodserviceResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.status = null;
      this.freespace = null;
      this.motionActive = null;
      this.result = null;
    }
    else {
      if (initObj.hasOwnProperty('status')) {
        this.status = initObj.status
      }
      else {
        this.status = 0;
      }
      if (initObj.hasOwnProperty('freespace')) {
        this.freespace = initObj.freespace
      }
      else {
        this.freespace = 0;
      }
      if (initObj.hasOwnProperty('motionActive')) {
        this.motionActive = initObj.motionActive
      }
      else {
        this.motionActive = false;
      }
      if (initObj.hasOwnProperty('result')) {
        this.result = initObj.result
      }
      else {
        this.result = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type hexapodserviceResult
    // Serialize message field [status]
    bufferOffset = _serializer.int32(obj.status, buffer, bufferOffset);
    // Serialize message field [freespace]
    bufferOffset = _serializer.int32(obj.freespace, buffer, bufferOffset);
    // Serialize message field [motionActive]
    bufferOffset = _serializer.bool(obj.motionActive, buffer, bufferOffset);
    // Serialize message field [result]
    bufferOffset = _serializer.string(obj.result, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type hexapodserviceResult
    let len;
    let data = new hexapodserviceResult(null);
    // Deserialize message field [status]
    data.status = _deserializer.int32(buffer, bufferOffset);
    // Deserialize message field [freespace]
    data.freespace = _deserializer.int32(buffer, bufferOffset);
    // Deserialize message field [motionActive]
    data.motionActive = _deserializer.bool(buffer, bufferOffset);
    // Deserialize message field [result]
    data.result = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.result.length;
    return length + 13;
  }

  static datatype() {
    // Returns string type for a message object
    return 'hexapodservice/hexapodserviceResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '84ae386391a6712ba3f1d0cdfd23bad0';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int32 status
    int32 freespace
    bool motionActive
    string result
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new hexapodserviceResult(null);
    if (msg.status !== undefined) {
      resolved.status = msg.status;
    }
    else {
      resolved.status = 0
    }

    if (msg.freespace !== undefined) {
      resolved.freespace = msg.freespace;
    }
    else {
      resolved.freespace = 0
    }

    if (msg.motionActive !== undefined) {
      resolved.motionActive = msg.motionActive;
    }
    else {
      resolved.motionActive = false
    }

    if (msg.result !== undefined) {
      resolved.result = msg.result;
    }
    else {
      resolved.result = ''
    }

    return resolved;
    }
};

module.exports = hexapodserviceResult;
